"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['mec_struct.py', 'libmmec.debug.dylib']
OPTIONS = {
    'argv_emulation': True,
    'no_chdir': True,
    'iconfile': 'vimtag.icns',
    'includes': ['webview', 'pyaudio', 'portaudio', 'threading', 'requests', 'chardet'],
    'plist': {
     'CFBundleName': 'main',
     'CFBundleDisplayName': 'vimtag',
     'CFBundleIdentifier': 'www.vimtag.com',
     'CFBundleVersion': '0.1.0',
     'CFBundleShortVersionString': '0.1',
     'LSUIElement': False, # 禁止 Dock 栏图标显示
     'NSMicrophoneUsageDescription': '需要访问麦克风以进行音频录制',
     'NSAppleEventsUsageDescription': '需要获取全屏权限'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
