function meval(b){try{return eval("("+b+")")}catch(c){return null}}function mobj_merge(b,c){var a,d,e,f;if(!c)return b;for(f in c)if(void 0!=(d=c[f])&&null!=d)if(d.constructor===Array){b[f]=e=[];a=0;for(len=d.length;a<len;a++)e[a]=d[a]}else if("object"!=typeof d)b[f]=d;else{if(void 0==(e=b[f])||null==e)b[f]=e={};obj_merge(e,d)}return b}
(function(b,c,a,d,e){d=d.prototype;c=c.prototype;a=a.prototype;e=e.prototype;c.cmp=function(a){var c,b,d=Math.min(this.length,a.length);for(c=0;c<d;c++)if(b=this.charCodeAt(c)-a.charCodeAt(c))return b;return this.length-a.length};c.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};a.toString1=function(){var a=this.getMonth()+1,c=this.getDate(),b=this.getHours(),d=this.getMinutes(),e=this.getSeconds();return this.getFullYear()+"\u5e74"+(10>a?"0":"")+a+"\u6708"+(10>c?"0":"")+c+"\u65e5"+(10>
b?"0":"")+b+":"+(10>d?"0":"")+d+":"+(10>e?"0":"")+e};d.filter=d.filter||function(a,c){var b,d,e=this.length,g=[];if("function"!=typeof a)throw new TypeError;for(b=0;b<e;b++)b in this&&(d=this[b],a.call(c,d,b,this)&&g.push(d));return g};d.some=d.some||function(a,c){var b,d=this.length;if("function"!=typeof a)throw new TypeError;for(b=0;b<d;b++)if(b in this&&a.call(c,this[b],b,this))return!0;return!1};d.forEach=d.forEach||function(a,c){var b,d=this.length;if("function"!=typeof a)throw new TypeError;
for(b=0;b<d;b++)b in this&&a.call(c,this[b],b,this)};(b.publisher=function(){this.subscribers=[]}).prototype.deliver=function(){for(var b=0,a,c=this.subscribers,d=c.length;b<d;)a=c[b],this.filter&&!this.filter(a,arguments)?b++:(a.fn.apply(a.fn,arguments),a=c[s_length],d>a?d=a:b++);return this};e.subscribe=function(a){var b,c=1,d={},e=this;if(!a.subscribers.some(function(a){return a.fn===e})){for(b=arguments.length;c<b;c++)d["arg"+(c-1)]=arguments[c];d.fn=e;a.subscribers.push(d)}return e};e.unsubscribe=
function(a){var b=this;a.subscribers=a.subscribers.filter(function(a){return a.fn!==b});return b}})(window,String,Date,Array,Function);function is_ancestor(b,c){var a,d=document.body;if(b==d)return!0;for(a=c.parentNode;a&&a!=d;a=a.parentNode)if(b===a)return!0;return!1}function getElementsByClass(b,c,a){var d=[];null==c&&(c=document);null==a&&(a="*");c=c.getElementsByTagName(a);a=c.length;b=RegExp("(^|\\s)"+b+"(\\s|$)");for(j=i=0;i<a;i++)b.test(c[i].className)&&(d[j]=c[i],j++);return d}
(function(b){function c(a,b){var e=b||document;switch(typeof a){case "string":var f=a.substring(1);switch(a.charAt(0)){case "#":return e.getElementById(f);case ".":return e.getElementsByClassName?e.getElementsByClassName(f):getElementsByClass(f,e);case "/":return e.getElementsByTagName(f);default:return e.getElementsByName(a)}case "object":return a;case "function":c.funcs.push(a)}}c.funcs=[];c.loaded=!1;c.run=function(){if(!c.loaded){for(var a=0;a<c.funcs.length;a++)c.funcs[a]();c.loaded=!0;delete c.funcs;
delete c.run}};b.addEventListener?b.addEventListener("load",c.run,!1):b.attachEvent?b.attachEvent("onload",c.run):b.onload=c.run;c.service_gid=1052078;c.ie6=0<=navigator.userAgent.indexOf("MSIE 6.");c.ie=0<=navigator.userAgent.indexOf("MSIE");b.hehe=b.mx=c})(window);
function sound_play(b,c){var a=window.snd_player;a&&(hack.ie||(a.innerHTML=""),a.parentNode.removeChild(a));window.snd_player=a=document.createElement(hack.ie?"embed":"bgsound");a.style.cssText="width:1px;height:1px;left:0px;top:0px;";a.src=hack.ie?b:c;hack.ie?a.src=b:a.innerHTML="<embed width='0' height='0' src='"+c+"'></embed>";document.body.appendChild(a)}
function dom_get_item_by_name(b,c,a){if(nodes=b.getElementsByTagName(c))for(node_index=0;node_index<nodes.length;++node_index)if(node=nodes[node_index],a==node.getAttribute("name"))return node;return null}(function(){var b,c,a,d,e=document;window.title_twinkle=function(f){a&&(clearInterval(a),a=null,b&&(e.title=b));f&&(b=e.title,e.title=c=f,a=setInterval(function(){e.title=(d=!d)?b:c},1E3))}})();
function insert_after(b,c){c.nextSibling?c.parentNode.insertBefore(b,c.nextSibling):c.parentNode.appendChild(b)}function remove_self(b){b&&b.parentNode&&b.parentNode.removeChild(b);return b}function get_x(b){for(var c=0;b;)c+=b.offsetLeft,b=b.offsetParent;return c}function get_y(b){for(var c=0,a=b;a;a=a.offsetParent)c+=a.offsetTop;for(a=b.parentNode;a&&a!=document.body;a=a.parentNode)a.scrollTop&&(c-=a.scrollTop);return c}
function viewport_width(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth}function viewport_height(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight};
